// <auto-generated />
using System;
using FichApp.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930115650_CreateAndSeedFichApp")]
    partial class CreateAndSeedFichApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichApp.Models.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Checkin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Checkout")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TimeSpent")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Timesheets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Checkin = new DateTime(2024, 9, 30, 13, 56, 49, 720, DateTimeKind.Local).AddTicks(8726),
                            TimeSpent = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Checkin = new DateTime(2024, 9, 30, 13, 56, 49, 720, DateTimeKind.Local).AddTicks(8794),
                            Checkout = new DateTime(2024, 9, 30, 18, 57, 12, 720, DateTimeKind.Local).AddTicks(8795),
                            TimeSpent = new TimeSpan(0, 5, 0, 23, 0)
                        },
                        new
                        {
                            Id = 3,
                            Checkin = new DateTime(2024, 9, 30, 13, 56, 49, 720, DateTimeKind.Local).AddTicks(8800),
                            TimeSpent = new TimeSpan(0, 5, 0, 23, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
