// <auto-generated />
using System;
using FichApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichApp.Models.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Checkin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Checkout")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TimeSpent")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Timesheets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Checkin = new DateTime(2024, 9, 26, 13, 24, 30, 499, DateTimeKind.Local).AddTicks(3653),
                            TimeSpent = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Checkout = new DateTime(2024, 9, 26, 18, 24, 53, 499, DateTimeKind.Local).AddTicks(3701),
                            TimeSpent = new TimeSpan(0, 5, 0, 23, 0)
                        },
                        new
                        {
                            Id = 3,
                            Checkin = new DateTime(2024, 9, 26, 13, 24, 30, 499, DateTimeKind.Local).AddTicks(3706),
                            TimeSpent = new TimeSpan(0, 5, 0, 23, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
